# Generated by Django 5.2.8 on 2026-02-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_price_fields_to_decimal'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('MEN', 'Men'), ('WOMEN', 'Women')], default='MEN', max_length=10),
        ),
    ]
