# Generated by Django 5.2.8 on 2026-02-28 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_category_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_image',
        ),
    ]
