# Generated by Django 5.2.8 on 2026-03-05 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_category_category_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['created_at']},
        ),
    ]
